version: '3'
services:

  category:
    build: './category'
    ports:
      - "5002:5002"

  template:
    build: './template'
    ports:
      - "5003:5003"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - category
      - template