version: '3'
services:

  category:
    build: './category'
    ports:
      - "5002:5000"
    depends_on: 
      - db
    environment:
      - DATABASE_URL

  template:
    build: './template'
    ports:
      - "5003:5000"
    depends_on: 
      - db
    environment:
      - DATABASE_URL
  
  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - category
      - template