name: Run Test

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
  NODE_ENV: test

on:
  push:
    branches: [ master ]

jobs:
  run_api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Category Environment Variables
        run: |
          pwd
          cd category
          ls -la