name: Run Test

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
  NODE_ENV: test

on:
  push:
    branches: [ master ]

jobs:
  run_api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Category Environment Variables
        run: |
          cd ./category
          chmod +x ./scripts/setup.sh
          ./scripts/setup.sh
        shell: bash
      - name: Show Category .env file content
        run: |
          pwd
          ls -la
          cat .env
      - name: Install Category dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - name: Set Up Template Environment Variables
        run: |
          cd ../
          cd ./template
          chmod +x ./scripts/setup.sh
          ./scripts/setup.sh
        shell: bash
      - name: Show Template .env file content
        run: |
          pwd
          ls -la
          cat .env
      - name: Install Template dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - name: Run unit tests
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: cd ../
      - run: npm ci
      - run: npm run test
  
